# ==================
# Project Details
# ==================
name: "jaffle_shop"
config-version: 2
version: "1.0.0"
profile: "duckdb"

# ==================
# File Path Configs
# ==================
test-paths:
- "tests"
clean-targets:
- "target"
- "dbt_packages"
snapshot-paths:
- "snapshots"
seed-paths:
- "seeds"
model-paths:
- "models"
- "prophecy-sources"
analysis-paths:
- "analyses"
macro-paths:
- "macros"
target-path: "target"

# ==================
# Variable Configs
# ==================
vars:
  truncate_timespan_to: '{{ current_timestamp() }}'

# ==================
# Model Configs
# ==================
models:
  jaffle_shop:
    marts: {}
    staging: {}
