# duckdb:
#   outputs:
#     dev:
#       type: duckdb
#       path: "{{ env_var('JAFFLE_DB_PATH', './reports/jaffle_shop.duckdb') }}"
#       database: "{{ env_var('JAFFLE_DB_NAME', 'jaffle_shop') }}"
#       schema: "{{ env_var('JAFFLE_TARGET_SCHEMA', 'analytics') }}"
#       threads: 4
#   target: dev

postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      port: 5432
      user: dbt
      password: dbt
      # password: ""
      dbname: dbt # or database instead of dbname
      schema: "public"
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening conne